# ========== GÜNCELLENECEK DOSYA: worker/pyproject.toml ==========
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-worker"
version = "0.1.0"
description = "The Celery worker for the AzuraForge Platform. Discovers and runs pipeline plugins."
requires-python = ">=3.8"
dependencies = [
    # Worker'ın kendisi doğrudan Learner'a değil, eklentilere ihtiyaç duyar.
    # Ama eklentilerin çalışması için Learner gerektiğinden, test ortamı için ekleyebiliriz.
    "azuraforge-learner @ git+https://github.com/AzuraForge/learner.git@main",
    
    # Geliştirme ve test sırasında bu eklentinin kurulu olmasını sağlıyoruz.
    "azuraforge-app-stock-predictor @ git+https://github.com/AzuraForge/app-stock-predictor.git@main",
    
    "celery[redis]",
    "pyyaml",
]

[project.scripts]
start-worker = "azuraforge_worker.main:run_celery_worker"