[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-worker"
version = "0.2.0"
description = "The Celery worker for the AzuraForge Platform. Discovers and runs pipeline plugins."
requires-python = ">=3.8"
dependencies = [
    # === DEĞİŞİKLİK BURADA ===
    # @main yerine kararlı versiyon etiketi kullanılıyor.
    "azuraforge-app-stock-predictor @ git+https://github.com/AzuraForge/app-stock-predictor.git@v0.1.0",
    # === DEĞİŞİKLİK SONU ===
    "celery[redis]",
    "pyyaml",
    "SQLAlchemy",
    "psycopg2-binary",
]

[project.scripts]
start-worker = "azuraforge_worker.main:run_celery_worker"