# ========== DOSYA: worker/pyproject.toml ==========
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azuraforge-worker"
version = "0.1.0"
description = "The Celery worker for processing background tasks for the AzuraForge Platform."
requires-python = ">=3.8"
dependencies = [
    # Hem learner'a hem de core'a ihtiyacı olacak.
    # learner'ı istemek, core'u da getirecektir.
    "azuraforge-learner @ git+https://github.com/AzuraForge/learner.git@main",
    #"azuraforge-applications @ git+https://github.com/AzuraForge/applications.git@main",
    "azuraforge-app-stock-predictor @ git+https://github.com/AzuraForge/app-stock-predictor.git@main",
    
    # Worker için gerekli paketler
    "celery[redis]",
    "python-dotenv",
    "pyyaml",
]

[project.scripts]
start-worker = "azuraforge_worker.main:run_celery_worker"