name: AzuraForge Worker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Worker'ın bağımlılıklarını kur (versiyon etiketleriyle)
        pip install git+https://github.com/AzuraForge/app-stock-predictor.git@v0.1.0
        # Worker'ın kendisini kur (test bağımlılıkları varsa [dev] eklenir)
        pip install -e .

    - name: Check code format with Black
      run: |
        pip install black
        black --check .
    
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        # Worker için henüz test yazmadık, bu adım şimdilik sadece pytest'in çalışıp
        # hiç test bulamadığını doğrulayacak ve hata vermeyecektir.
        pip install pytest
        pytest